services:
  db:
    image: postgres:15
    container_name: securesched_db
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: securesched_backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

volumes:
  postgres_data:
